# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_7Z "")
SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "OFF")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_FREEBSD "OFF")
SET(CPACK_BINARY_IFW "OFF")
SET(CPACK_BINARY_NSIS "OFF")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_PRODUCTBUILD "")
SET(CPACK_BINARY_RPM "OFF")
SET(CPACK_BINARY_STGZ "ON")
SET(CPACK_BINARY_TBZ2 "OFF")
SET(CPACK_BINARY_TGZ "ON")
SET(CPACK_BINARY_TXZ "OFF")
SET(CPACK_BINARY_TZ "ON")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_BUILD_SOURCE_DIRS "/home/brandon/Projects/root-6.10.04;/home/brandon/Projects/root-6.10.04/root")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENTS_ALL "LLVMAnalysis;LLVMAsmParser;LLVMAsmPrinter;LLVMBitReader;LLVMBitWriter;LLVMCodeGen;LLVMCore;LLVMCoverage;LLVMDebugInfoCodeView;LLVMDebugInfoDWARF;LLVMDebugInfoPDB;LLVMExecutionEngine;LLVMGlobalISel;LLVMIRReader;LLVMInstCombine;LLVMInstrumentation;LLVMInterpreter;LLVMLTO;LLVMLibDriver;LLVMLineEditor;LLVMLinker;LLVMMC;LLVMMCDisassembler;LLVMMCJIT;LLVMMCParser;LLVMMIRParser;LLVMObjCARCOpts;LLVMObject;LLVMObjectYAML;LLVMOption;LLVMOrcJIT;LLVMPasses;LLVMProfileData;LLVMRuntimeDyld;LLVMScalarOpts;LLVMSelectionDAG;LLVMSupport;LLVMSymbolize;LLVMTableGen;LLVMTarget;LLVMTransformUtils;LLVMVectorize;LLVMX86AsmParser;LLVMX86AsmPrinter;LLVMX86CodeGen;LLVMX86Desc;LLVMX86Disassembler;LLVMX86Info;LLVMX86Utils;LLVMipo;LTO;Unspecified;applications;c-index-test;clang-headers;clangAST;clangASTMatchers;clangAnalysis;clangBasic;clangCodeGen;clangDriver;clangDynamicASTMatchers;clangEdit;clangFormat;clangFrontend;clangFrontendTool;clangIndex;clangLex;clangParse;clangRewrite;clangRewriteFrontend;clangSema;clangSerialization;clangTooling;clangToolingCore;clingInterpreter;clingMetaProcessor;clingUtils;headers;libclang;libclang-headers;libraries;llvm-headers;tests")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_GENERATOR "TGZ;TBZ2")
SET(CPACK_IGNORE_FILES "/home/brandon/Projects/root-6.10.04/root;/home/brandon/Projects/root-6.10.04/tests;~$;/CVS/;/.svn/;/\\\\.svn/;/.git/;/\\\\.git/;\\\\.swp$;\\\\.swp$;\\.swp;\\\\.#;/#")
SET(CPACK_INSTALLED_DIRECTORIES "/home/brandon/Projects/root-6.10.04;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "/home/brandon/Projects/root-6.10.04/cmake/modules")
SET(CPACK_NSIS_DISPLAY_NAME "root_v6.10.04")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "root_v6.10.04")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/brandon/Projects/root-6.10.04/root/CPackConfig.cmake")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION "ROOT project")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/brandon/Projects/root-6.10.04/root/README.txt")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "ROOT project")
SET(CPACK_PACKAGE_EXECUTABLES "root;ROOT")
SET(CPACK_PACKAGE_FILE_NAME "ROOT-6.10.04-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "root_v6.10.04")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "root_v6.10.04")
SET(CPACK_PACKAGE_NAME "ROOT")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "HEPSoft")
SET(CPACK_PACKAGE_VERSION "6.10.04")
SET(CPACK_PACKAGE_VERSION_MAJOR "6")
SET(CPACK_PACKAGE_VERSION_MINOR "10")
SET(CPACK_PACKAGE_VERSION_PATCH "04")
SET(CPACK_PROJECT_CONFIG_FILE "/home/brandon/Projects/root-6.10.04/root/CMakeCPackOptions.cmake")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/brandon/Projects/root-6.10.04/root/LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "/home/brandon/Projects/root-6.10.04/root/README.txt")
SET(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.10/Templates/CPack.GenericWelcome.txt")
SET(CPACK_RPM_PACKAGE_SOURCES "ON")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_7Z "")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ;TBZ2")
SET(CPACK_SOURCE_IGNORE_FILES "/home/brandon/Projects/root-6.10.04/root;/home/brandon/Projects/root-6.10.04/tests;~$;/CVS/;/.svn/;/\\\\.svn/;/.git/;/\\\\.git/;\\\\.swp$;\\\\.swp$;\\.swp;\\\\.#;/#")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/brandon/Projects/root-6.10.04;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/brandon/Projects/root-6.10.04/root/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "ROOT-6.10.04-Source")
SET(CPACK_SOURCE_RPM "OFF")
SET(CPACK_SOURCE_STRIP_FILES "")
SET(CPACK_SOURCE_TBZ2 "ON")
SET(CPACK_SOURCE_TGZ "ON")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TXZ "ON")
SET(CPACK_SOURCE_TZ "ON")
SET(CPACK_SOURCE_ZIP "OFF")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/brandon/Projects/root-6.10.04/root/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
